[Feature] [WRS-2078] Implement data connector authorization
chili-publish/studio-ui pull request #218
Opened 2024-10-31 13:34 UTC by alexandraFlavia9

This PR implements data connector configuration

## Related tickets

-   [WRS-2078](https://chilipublishintranet.atlassian.net/browse/WRS-2078)

## Screenshots

[WRS-2078]: https://chilipublishintranet.atlassian.net/browse/WRS-2078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-11-01 16:05 UTC, psamusev requested changes

2024-11-01 16:05 UTC, psamusev commented on src/components/connector-authentication/useConnectorAuthentication.ts
> +export type ConnectorAuthenticationFlow = {
Can we separate authentication process management from authentication flows? I don't like idea of using `useConnectorAuthenticationResult();` in this hook

2024-11-01 16:05 UTC, psamusev commented on src/components/dataSource/DataSource.tsx
> +    const [firstRowInfo, setFirstRowInfo] = useState('');
seems like it should be `currentRow` because you will have possibility to switch in follow up tickets

2024-11-01 16:05 UTC, psamusev commented on src/components/dataSource/DataSource.tsx
> +
If I'm not mistaken limit should be 15 according to ticket requirements

2024-11-01 16:05 UTC, psamusev commented on src/components/layout-panels/leftPanel/LeftPanel.tsx
> +                {isDocumentLoaded && isSandboxMode ? <DataSource /> : null}
It should be available in the regular mode as well. Please just hide it under FF `STUDIO_DATA_SOURCE` for now

2024-11-01 16:06 UTC, psamusev commented on src/components/dataSource/DataSource.tsx
>      const [firstRowInfo, setFirstRowInfo] = useState('');
seems like it should be currentRow because you will have possibility to switch in follow up tickets

2024-11-04 10:41 UTC, psamusev commented on src/components/connector-authentication/useConnectorAuthentication.ts
> +    const [pendingAuthentication, setpendingAuthentication] = useState<ConnectorAuthenticationFlow[]>([]);
```suggestion
    const [pendingAuthentication, setPendingAuthentication] = useState<ConnectorPendingAuthentication[]>([]);
```

2024-11-04 10:41 UTC, psamusev commented on src/components/connector-authentication/useConnectorAuthentication.ts
> +export type ConnectorAuthenticationFlow = {
```suggestion
export type ConnectorPendingAuthentication = {
```

2024-11-04 13:29 UTC, psamusev commented on src/components/connector-authentication/useConnectorAuthentication.ts
> +                result: null,
seems like should be removed

2024-11-04 13:29 UTC, psamusev commented on src/components/connector-authentication/useConnectorAuthentication.ts
> +                                        connectorName: authenticationProcess.connectorName,
I know it's rare real case, but since `connectorName` doesn't suppose to be unique, can we do identification based on `connectorId` instead?

2024-11-04 14:24 UTC, psamusev approved these changes

2024-11-08 08:51 UTC, abdelhalimkhouas approved these changes

2024-11-08 08:54 UTC, merged