WRS-2173 - studio ui multi-page
chili-publish/studio-ui pull request #244
Opened 2024-12-04 15:46 UTC by smereuta

This PR

## Related tickets

-   [WRS-2173](https://chilipublishintranet.atlassian.net/browse/WRS-2173)

## Screenshots

2024-12-05 11:36 UTC, smereuta commented on src/components/pagesPanel/Pages.tsx
> +        const timeoutId = setTimeout(updateSnapshots, 1000);
if changing a variable that modifies content of template, changes should be reflected also in snapshots. 
eg: boolean variable that modifies show/hide frame in template

2024-12-05 14:10 UTC, psamusev requested changes

2024-12-05 14:10 UTC, psamusev commented on src/components/pagesPanel/Pages.tsx
> +                    const newSnap = (await window.SDK.page.getSnapshot(pageId)) as unknown as Uint8Array;
won't be executed in parallel. You have to do similar mapping form as in line 33

2024-12-05 15:49 UTC, smereuta commented on src/components/pagesPanel/Pages.tsx
> +        const timeoutId = setTimeout(updateSnapshots, 1000);
kept the same implementation as in workspace, where requirement was to debounce snapshot every second, and if there are multiple and fast changes to template, get once the latest snapshot

2024-12-10 09:03 UTC, psamusev approved these changes

2024-12-11 12:17 UTC, psamusev approved these changes

2024-12-11 12:34 UTC, merged